from dataclasses import dataclass


@dataclass(frozen=True)
class ProducerInfo:
    name: str
    category: str
    description: str
    interpretation: str
    confidence: int
    risk_level: str
    common_uses: list[str]
    correlate_with: list[str]


class ProducerDatabase:
    """
    Base de conhecimento de Producers/Creators/Softwares.

    Esta classe não analisa arquivos.
    Ela apenas interpreta tecnicamente um valor já extraído dos metadados.
    """

    PRODUCERS: dict[str, ProducerInfo] = {
        "itext": ProducerInfo(
            name="iText",
            category="Biblioteca PDF",
            description="Biblioteca amplamente utilizada para criação, manipulação e processamento de arquivos PDF.",
            interpretation="A presença de iText indica que o PDF foi gerado ou processado por aplicação que utiliza essa biblioteca. Isoladamente, não indica adulteração.",
            confidence=95,
            risk_level="Informativo",
            common_uses=["geração de PDF", "assinatura eletrônica", "sistemas web", "processamento documental"],
            correlate_with=["CreateDate", "ModifyDate", "assinatura digital", "XMP", "incremental updates"],
        ),
        "itextsharp": ProducerInfo(
            name="iTextSharp",
            category="Biblioteca PDF",
            description="Versão .NET da biblioteca iText, utilizada em aplicações para geração e manipulação de PDFs.",
            interpretation="Pode indicar geração automatizada ou processamento documental por sistema interno.",
            confidence=95,
            risk_level="Informativo",
            common_uses=["sistemas corporativos", "geração automatizada", "contratos eletrônicos"],
            correlate_with=["datas do PDF", "hash", "assinatura digital", "logs do sistema"],
        ),
        "pdfium": ProducerInfo(
            name="PDFium",
            category="Motor PDF",
            description="Motor de renderização e processamento de PDF utilizado em navegadores e aplicações baseadas em Chromium.",
            interpretation="Pode indicar visualização, renderização, impressão ou exportação por aplicação baseada em Chromium.",
            confidence=90,
            risk_level="Informativo",
            common_uses=["Chrome", "Edge", "Chromium", "renderização PDF", "visualizadores embutidos"],
            correlate_with=["Creator", "User-Agent", "datas", "estrutura PDF"],
        ),
        "ghostscript": ProducerInfo(
            name="Ghostscript",
            category="Conversor/Processador PDF",
            description="Ferramenta utilizada para conversão, otimização, compressão e reprocessamento de documentos PDF.",
            interpretation="Pode indicar que o arquivo passou por conversão, compressão, impressão virtual ou reprocessamento.",
            confidence=95,
            risk_level="Atenção",
            common_uses=["conversão PDF", "compressão", "normalização", "impressão virtual"],
            correlate_with=["CreateDate", "ModifyDate", "tamanho do arquivo", "estrutura interna"],
        ),
        "pdfbox": ProducerInfo(
            name="Apache PDFBox",
            category="Biblioteca PDF",
            description="Biblioteca Java utilizada para criação, extração, manipulação e validação de documentos PDF.",
            interpretation="Pode indicar geração ou manipulação automatizada por aplicação Java.",
            confidence=90,
            risk_level="Informativo",
            common_uses=["sistemas Java", "extração de texto", "geração PDF", "processamento documental"],
            correlate_with=["metadados", "assinatura", "logs de sistema"],
        ),
        "skia": ProducerInfo(
            name="Skia/PDF",
            category="Motor gráfico/PDF",
            description="Biblioteca gráfica utilizada em navegadores e aplicações para renderização e geração de documentos.",
            interpretation="Frequentemente associada a PDFs gerados por navegadores, impressão para PDF ou aplicações baseadas em Chromium.",
            confidence=90,
            risk_level="Informativo",
            common_uses=["Chrome", "Edge", "impressão para PDF", "renderização"],
            correlate_with=["Creator", "User-Agent", "datas", "metadados XMP"],
        ),
        "quartz": ProducerInfo(
            name="Quartz PDFContext",
            category="Apple/macOS",
            description="Componente do macOS/iOS utilizado para geração e processamento de documentos PDF.",
            interpretation="Pode indicar geração ou exportação em ambiente Apple, como Preview, Safari ou aplicações iOS/macOS.",
            confidence=90,
            risk_level="Informativo",
            common_uses=["macOS", "iOS", "Preview", "Safari", "exportação PDF"],
            correlate_with=["dispositivo declarado", "User-Agent", "datas", "ImageIO"],
        ),
        "cairo": ProducerInfo(
            name="Cairo",
            category="Biblioteca gráfica",
            description="Biblioteca gráfica utilizada para renderização e geração de documentos, inclusive PDF.",
            interpretation="Pode indicar geração por aplicação Linux, sistemas gráficos ou ferramentas automatizadas.",
            confidence=85,
            risk_level="Informativo",
            common_uses=["Linux", "relatórios automatizados", "renderização gráfica"],
            correlate_with=["Creator", "ambiente de sistema", "metadados"],
        ),
        "mupdf": ProducerInfo(
            name="MuPDF",
            category="Motor PDF",
            description="Motor leve para leitura, renderização e manipulação de documentos PDF.",
            interpretation="Pode indicar processamento por ferramenta de visualização, conversão ou manipulação PDF.",
            confidence=85,
            risk_level="Informativo",
            common_uses=["visualizadores PDF", "conversão", "renderização"],
            correlate_with=["estrutura PDF", "datas", "metadados"],
        ),
        "wkhtmltopdf": ProducerInfo(
            name="wkhtmltopdf",
            category="Conversor HTML para PDF",
            description="Ferramenta utilizada para converter páginas HTML em arquivos PDF.",
            interpretation="Pode indicar que o documento foi gerado a partir de página web ou template HTML.",
            confidence=95,
            risk_level="Informativo",
            common_uses=["relatórios web", "contratos online", "boletos", "templates HTML"],
            correlate_with=["URL de origem", "logs", "User-Agent", "datas"],
        ),
        "prince": ProducerInfo(
            name="PrinceXML",
            category="Conversor HTML/XML para PDF",
            description="Ferramenta profissional para geração de PDFs a partir de HTML, XML e CSS.",
            interpretation="Indica provável geração automatizada por sistema de publicação ou relatório.",
            confidence=90,
            risk_level="Informativo",
            common_uses=["relatórios", "documentos corporativos", "publicação automatizada"],
            correlate_with=["Creator", "datas", "sistema emissor"],
        ),
        "reportlab": ProducerInfo(
            name="ReportLab",
            category="Biblioteca PDF Python",
            description="Biblioteca Python usada para geração programática de documentos PDF.",
            interpretation="Pode indicar geração automatizada por script ou sistema em Python.",
            confidence=95,
            risk_level="Informativo",
            common_uses=["relatórios", "sistemas Python", "documentos automatizados"],
            correlate_with=["logs", "datas", "sistema emissor"],
        ),
        "tcpdf": ProducerInfo(
            name="TCPDF",
            category="Biblioteca PDF PHP",
            description="Biblioteca PHP utilizada para geração de documentos PDF.",
            interpretation="Pode indicar geração por sistema web em PHP.",
            confidence=95,
            risk_level="Informativo",
            common_uses=["sistemas PHP", "boletos", "contratos", "relatórios web"],
            correlate_with=["URL", "logs do servidor", "datas"],
        ),
        "fpdf": ProducerInfo(
            name="FPDF",
            category="Biblioteca PDF PHP",
            description="Biblioteca PHP utilizada para geração simples de arquivos PDF.",
            interpretation="Pode indicar geração automatizada por sistema web ou script PHP.",
            confidence=90,
            risk_level="Informativo",
            common_uses=["sistemas PHP", "relatórios", "documentos simples"],
            correlate_with=["logs", "URL", "datas"],
        ),
        "dompdf": ProducerInfo(
            name="Dompdf",
            category="Conversor HTML para PDF",
            description="Biblioteca PHP que converte HTML/CSS em PDF.",
            interpretation="Pode indicar que o documento foi gerado a partir de template HTML por sistema web.",
            confidence=90,
            risk_level="Informativo",
            common_uses=["sistemas web", "relatórios", "contratos", "HTML para PDF"],
            correlate_with=["URL", "logs", "template", "datas"],
        ),
        "adobe acrobat": ProducerInfo(
            name="Adobe Acrobat",
            category="Editor/Processador PDF",
            description="Software amplamente utilizado para criação, edição, assinatura e manipulação de PDFs.",
            interpretation="Pode indicar criação, edição, otimização, assinatura ou reprocessamento por Adobe Acrobat.",
            confidence=95,
            risk_level="Atenção",
            common_uses=["edição PDF", "assinatura", "otimização", "organização de páginas"],
            correlate_with=["ModifyDate", "incremental updates", "assinaturas", "XMP"],
        ),
        "acrobat distiller": ProducerInfo(
            name="Acrobat Distiller",
            category="Conversor PDF",
            description="Componente Adobe utilizado para conversão de arquivos PostScript em PDF.",
            interpretation="Pode indicar geração por fluxo de impressão, editoração ou conversão profissional.",
            confidence=95,
            risk_level="Informativo",
            common_uses=["PostScript para PDF", "editoração", "impressão profissional"],
            correlate_with=["Creator", "datas", "estrutura PDF"],
        ),
        "adobe pdf library": ProducerInfo(
            name="Adobe PDF Library",
            category="Biblioteca PDF",
            description="Biblioteca Adobe utilizada por aplicações para criação e manipulação de PDFs.",
            interpretation="Pode indicar geração ou processamento por software baseado em tecnologia Adobe.",
            confidence=90,
            risk_level="Informativo",
            common_uses=["sistemas corporativos", "Adobe", "processamento PDF"],
            correlate_with=["Creator", "datas", "assinatura digital"],
        ),
        "indesign": ProducerInfo(
            name="Adobe InDesign",
            category="Editoração",
            description="Software profissional de editoração e diagramação.",
            interpretation="Pode indicar que o documento foi produzido em fluxo editorial ou gráfico.",
            confidence=95,
            risk_level="Informativo",
            common_uses=["diagramação", "materiais gráficos", "contratos diagramados", "publicações"],
            correlate_with=["Creator", "ModifyDate", "XMP"],
        ),
        "illustrator": ProducerInfo(
            name="Adobe Illustrator",
            category="Editor gráfico",
            description="Software de criação e edição vetorial.",
            interpretation="Pode indicar criação ou edição gráfica do documento.",
            confidence=95,
            risk_level="Atenção",
            common_uses=["arte vetorial", "layout", "edição gráfica", "exportação PDF"],
            correlate_with=["camadas", "XMP", "datas", "conteúdo visual"],
        ),
        "photoshop": ProducerInfo(
            name="Adobe Photoshop",
            category="Editor de imagem",
            description="Software de edição e manipulação de imagens.",
            interpretation="Em arquivos documentais, pode indicar processamento de imagem ou exportação a partir de editor gráfico.",
            confidence=95,
            risk_level="Atenção",
            common_uses=["edição de imagem", "exportação PDF", "tratamento visual"],
            correlate_with=["EXIF", "XMP", "ModifyDate", "histórico de edição"],
        ),
        "microsoft word": ProducerInfo(
            name="Microsoft Word",
            category="Editor de texto",
            description="Editor de texto utilizado para criação e exportação de documentos.",
            interpretation="Indica provável geração/exportação a partir de documento Word.",
            confidence=95,
            risk_level="Informativo",
            common_uses=["contratos", "petições", "relatórios", "exportação PDF"],
            correlate_with=["Author", "LastModifiedBy", "CreateDate", "ModifyDate"],
        ),
        "microsoft office": ProducerInfo(
            name="Microsoft Office",
            category="Suíte de escritório",
            description="Suíte utilizada para criação de documentos, planilhas e apresentações.",
            interpretation="Pode indicar geração ou exportação por aplicativos Office.",
            confidence=90,
            risk_level="Informativo",
            common_uses=["Word", "Excel", "PowerPoint", "exportação PDF"],
            correlate_with=["Author", "LastModifiedBy", "datas"],
        ),
        "microsoft print to pdf": ProducerInfo(
            name="Microsoft Print to PDF",
            category="Impressora virtual",
            description="Recurso do Windows para impressão virtual em PDF.",
            interpretation="Pode indicar que o documento foi recriado por impressão virtual, gerando uma nova versão PDF.",
            confidence=95,
            risk_level="Atenção",
            common_uses=["impressão virtual", "reexportação", "normalização PDF"],
            correlate_with=["CreateDate", "ModifyDate", "perda de metadados", "assinaturas removidas"],
        ),
        "libreoffice": ProducerInfo(
            name="LibreOffice",
            category="Suíte de escritório",
            description="Suíte aberta utilizada para criação e exportação de documentos.",
            interpretation="Indica provável geração/exportação por LibreOffice.",
            confidence=95,
            risk_level="Informativo",
            common_uses=["Writer", "Calc", "exportação PDF", "documentos administrativos"],
            correlate_with=["Creator", "datas", "Author"],
        ),
        "openoffice": ProducerInfo(
            name="OpenOffice",
            category="Suíte de escritório",
            description="Suíte aberta utilizada para criação e exportação de documentos.",
            interpretation="Indica provável geração/exportação por OpenOffice.",
            confidence=90,
            risk_level="Informativo",
            common_uses=["Writer", "Calc", "exportação PDF"],
            correlate_with=["Creator", "datas", "Author"],
        ),
        "chrome": ProducerInfo(
            name="Google Chrome",
            category="Navegador",
            description="Navegador que pode gerar PDFs por impressão ou salvamento de páginas.",
            interpretation="Pode indicar geração a partir de página web, visualizador interno ou impressão para PDF.",
            confidence=85,
            risk_level="Informativo",
            common_uses=["impressão web", "salvar como PDF", "portais de assinatura", "relatórios web"],
            correlate_with=["URL", "User-Agent", "Skia/PDF", "PDFium"],
        ),
        "chromium": ProducerInfo(
            name="Chromium",
            category="Navegador/Motor",
            description="Base de navegadores e aplicações que podem gerar ou renderizar PDFs.",
            interpretation="Pode indicar geração por navegador ou aplicação baseada em Chromium/Electron.",
            confidence=85,
            risk_level="Informativo",
            common_uses=["Chrome", "Edge", "Electron", "webview", "sistemas web"],
            correlate_with=["Skia/PDF", "PDFium", "User-Agent"],
        ),
        "edge": ProducerInfo(
            name="Microsoft Edge",
            category="Navegador",
            description="Navegador baseado em Chromium com capacidade de gerar PDFs por impressão/salvamento.",
            interpretation="Pode indicar geração por impressão de página web ou visualização interna.",
            confidence=85,
            risk_level="Informativo",
            common_uses=["impressão web", "salvar PDF", "portais"],
            correlate_with=["Skia/PDF", "PDFium", "User-Agent"],
        ),
        "firefox": ProducerInfo(
            name="Mozilla Firefox",
            category="Navegador",
            description="Navegador capaz de salvar ou imprimir páginas em PDF.",
            interpretation="Pode indicar geração de PDF a partir de conteúdo web.",
            confidence=80,
            risk_level="Informativo",
            common_uses=["salvar como PDF", "impressão web", "páginas HTML"],
            correlate_with=["URL", "Creator", "datas"],
        ),
        "ilovepdf": ProducerInfo(
            name="iLovePDF",
            category="Serviço online PDF",
            description="Serviço online utilizado para unir, dividir, comprimir, converter e manipular PDFs.",
            interpretation="Indica processamento por serviço externo online. Pode sugerir que o arquivo analisado não corresponde ao arquivo originário.",
            confidence=95,
            risk_level="Atenção",
            common_uses=["compressão", "união de PDFs", "conversão", "organização de páginas"],
            correlate_with=["CreateDate", "ModifyDate", "perda de assinatura", "metadados removidos"],
        ),
        "smallpdf": ProducerInfo(
            name="Smallpdf",
            category="Serviço online PDF",
            description="Serviço online para compressão, conversão e edição de PDFs.",
            interpretation="Pode indicar processamento externo posterior ao arquivo original.",
            confidence=95,
            risk_level="Atenção",
            common_uses=["compressão", "conversão", "merge", "split"],
            correlate_with=["datas", "metadados", "assinaturas"],
        ),
        "sejda": ProducerInfo(
            name="Sejda",
            category="Serviço online PDF",
            description="Ferramenta online/desktop para edição e manipulação de PDFs.",
            interpretation="Pode indicar edição, conversão ou reorganização documental.",
            confidence=90,
            risk_level="Atenção",
            common_uses=["edição PDF", "merge", "split", "compressão"],
            correlate_with=["ModifyDate", "metadados", "estrutura PDF"],
        ),
        "pdf24": ProducerInfo(
            name="PDF24",
            category="Ferramenta PDF",
            description="Ferramenta usada para criação, conversão e compressão de PDFs.",
            interpretation="Pode indicar processamento por ferramenta de conversão ou impressora virtual.",
            confidence=90,
            risk_level="Atenção",
            common_uses=["compressão", "conversão", "impressão virtual"],
            correlate_with=["datas", "metadados", "assinaturas"],
        ),
        "foxit": ProducerInfo(
            name="Foxit",
            category="Editor/Visualizador PDF",
            description="Software utilizado para visualização, edição e assinatura de PDFs.",
            interpretation="Pode indicar visualização, anotação, assinatura ou edição por Foxit.",
            confidence=90,
            risk_level="Atenção",
            common_uses=["edição PDF", "assinatura", "anotações", "visualização"],
            correlate_with=["ModifyDate", "incremental updates", "assinaturas"],
        ),
        "nitro": ProducerInfo(
            name="Nitro PDF",
            category="Editor PDF",
            description="Software de criação, edição e conversão de PDFs.",
            interpretation="Pode indicar edição, conversão ou reprocessamento por Nitro PDF.",
            confidence=90,
            risk_level="Atenção",
            common_uses=["edição", "conversão", "assinatura", "compressão"],
            correlate_with=["ModifyDate", "metadados", "assinaturas"],
        ),
        "pdfcreator": ProducerInfo(
            name="PDFCreator",
            category="Impressora virtual",
            description="Ferramenta de impressão virtual para geração de PDFs.",
            interpretation="Pode indicar recriação do documento por fluxo de impressão.",
            confidence=90,
            risk_level="Atenção",
            common_uses=["impressão virtual", "conversão", "geração PDF"],
            correlate_with=["CreateDate", "ModifyDate", "perda de metadados"],
        ),
        "bullzip": ProducerInfo(
            name="Bullzip PDF Printer",
            category="Impressora virtual",
            description="Impressora virtual para geração de documentos PDF.",
            interpretation="Pode indicar que o arquivo foi produzido por impressão virtual.",
            confidence=90,
            risk_level="Atenção",
            common_uses=["impressão virtual", "reexportação"],
            correlate_with=["datas", "estrutura", "metadados"],
        ),
        "cutepdf": ProducerInfo(
            name="CutePDF",
            category="Impressora virtual",
            description="Ferramenta de impressão virtual para PDF.",
            interpretation="Pode indicar geração/recriação por impressão virtual.",
            confidence=85,
            risk_level="Atenção",
            common_uses=["impressão virtual", "conversão"],
            correlate_with=["datas", "metadados", "assinaturas"],
        ),
        "docusign": ProducerInfo(
            name="DocuSign",
            category="Plataforma de assinatura eletrônica",
            description="Plataforma utilizada para assinatura eletrônica e gestão de envelopes digitais.",
            interpretation="Pode indicar fluxo formal de assinatura eletrônica. Recomenda-se correlacionar com certificados, logs, trilha de eventos e relatórios de auditoria.",
            confidence=95,
            risk_level="Informativo",
            common_uses=["assinatura eletrônica", "trilha de auditoria", "contratos"],
            correlate_with=["envelope ID", "audit trail", "certificado", "timestamp"],
        ),
        "clicksign": ProducerInfo(
            name="Clicksign",
            category="Plataforma de assinatura eletrônica",
            description="Plataforma brasileira de assinatura eletrônica.",
            interpretation="Pode indicar fluxo de assinatura eletrônica mediado por plataforma. Deve ser correlacionado com logs e evidências de autenticação.",
            confidence=95,
            risk_level="Informativo",
            common_uses=["assinatura eletrônica", "contratos", "logs"],
            correlate_with=["trilha de eventos", "IP", "geolocalização", "e-mail", "SMS"],
        ),
        "autentique": ProducerInfo(
            name="Autentique",
            category="Plataforma de assinatura eletrônica",
            description="Plataforma brasileira para assinatura eletrônica de documentos.",
            interpretation="Pode indicar assinatura eletrônica por plataforma. A validação depende dos registros técnicos disponibilizados.",
            confidence=95,
            risk_level="Informativo",
            common_uses=["assinatura eletrônica", "contratos", "certificados de assinatura"],
            correlate_with=["logs", "hash", "IP", "certificado de conclusão"],
        ),
        "zapsign": ProducerInfo(
            name="ZapSign",
            category="Plataforma de assinatura eletrônica",
            description="Plataforma de assinatura eletrônica utilizada em fluxos digitais.",
            interpretation="Pode indicar assinatura eletrônica em ambiente web. Deve ser correlacionado com trilha de auditoria e evidências de autenticação.",
            confidence=90,
            risk_level="Informativo",
            common_uses=["assinatura eletrônica", "contratos digitais"],
            correlate_with=["logs", "IP", "e-mail", "SMS", "selfie"],
        ),
        "canva": ProducerInfo(
            name="Canva",
            category="Editor gráfico online",
            description="Plataforma online para criação de peças gráficas e documentos.",
            interpretation="Em documentos formais, pode indicar criação ou reexportação gráfica do arquivo.",
            confidence=90,
            risk_level="Atenção",
            common_uses=["design", "templates", "exportação PDF", "peças gráficas"],
            correlate_with=["layout", "metadados", "datas", "conteúdo visual"],
        ),
        "gimp": ProducerInfo(
            name="GIMP",
            category="Editor de imagem",
            description="Software livre de edição de imagens.",
            interpretation="Pode indicar edição ou reprocessamento de imagem/documento.",
            confidence=90,
            risk_level="Atenção",
            common_uses=["edição de imagem", "exportação", "tratamento visual"],
            correlate_with=["EXIF", "XMP", "datas", "histórico de edição"],
        ),
        "whatsapp": ProducerInfo(
            name="WhatsApp",
            category="Mensageria",
            description="Aplicativo de mensagens que pode comprimir imagens, remover metadados e alterar características do arquivo.",
            interpretation="Pode indicar compartilhamento por mensageria, com possível perda de metadados originais.",
            confidence=85,
            risk_level="Atenção",
            common_uses=["compartilhamento", "compressão de imagem", "envio de documentos"],
            correlate_with=["EXIF", "tamanho do arquivo", "datas", "metadados ausentes"],
        ),
        "telegram": ProducerInfo(
            name="Telegram",
            category="Mensageria",
            description="Aplicativo de mensagens utilizado para envio de arquivos e imagens.",
            interpretation="Pode indicar trânsito por mensageria; dependendo do modo de envio, pode haver preservação ou perda de metadados.",
            confidence=80,
            risk_level="Atenção",
            common_uses=["envio de arquivo", "envio de imagem", "compartilhamento"],
            correlate_with=["EXIF", "tamanho", "datas", "nome do arquivo"],
        ),
    }

    @classmethod
    def find(cls, raw_value: str | None) -> ProducerInfo | None:
        if not raw_value:
            return None

        value = raw_value.lower()

        for key, producer in cls.PRODUCERS.items():
            if key in value:
                return producer

        return None